_DEBUG_MODE_ = False
DEFAULT_GEARMAN_PORT = 4730

PRIORITY_NONE = None
PRIORITY_LOW = 'LOW'
PRIORITY_HIGH = 'HIGH'

JOB_PENDING = 'PENDING'
JOB_QUEUED = 'QUEUED'
JOB_FAILED = 'FAILED'
JOB_COMPLETE = 'COMPLETE'